#include <buzzer.h>
#include "config.h"

void BuzzerInit(void)
{
    // Allow allocation of all timers
    ESP32PWM::allocateTimer(0);
    ESP32PWM::allocateTimer(1);
    ESP32PWM::allocateTimer(2);
    ESP32PWM::allocateTimer(3);
}

void startup_tone()
{
    tone(BUZZER_PIN, BUZZER_FREQ, 100); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                 // Stop sound...
    delay(10);

    tone(BUZZER_PIN, BUZZER_FREQ, 100); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                 // Stop sound...
    delay(10);

    tone(BUZZER_PIN, BUZZER_FREQ, 100); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                 // Stop sound...
    delay(10);

    tone(BUZZER_PIN, BUZZER_FREQ, 100); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                 // Stop sound...
    delay(10);
}
void success_tone()
{
    tone(BUZZER_PIN, BUZZER_FREQ, 100); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                 // Stop sound...
    delay(20);

    tone(BUZZER_PIN, BUZZER_FREQ, 100); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                 // Stop sound...
    delay(20);
}
void error_tone()
{
    tone(BUZZER_PIN, BUZZER_FREQ, 100); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                 // Stop sound...
    delay(20);

    tone(BUZZER_PIN, BUZZER_FREQ, 100); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                 // Stop sound...
    delay(20);

    tone(BUZZER_PIN, BUZZER_FREQ, 100); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                 // Stop sound...
    delay(20);
}

void WiFiStart_tone()
{
    tone(BUZZER_PIN, BUZZER_FREQ, 50); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                // Stop sound...
    delay(100);

    // tone(BUZZER_PIN, BUZZER_FREQ, 50); // Send 1KHz sound signal...
    // noTone(BUZZER_PIN);          // Stop sound...
    // delay(50);
}

void WiFiStop_tone()
{
    tone(BUZZER_PIN, BUZZER_FREQ, 50); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                // Stop sound...
    delay(50);

    tone(BUZZER_PIN, BUZZER_FREQ, 50); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                // Stop sound...
    delay(50);

    tone(BUZZER_PIN, BUZZER_FREQ, 50); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                // Stop sound...
    delay(50);
}

void HotspotStart_tone()
{
    tone(BUZZER_PIN, BUZZER_FREQ, 80); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                // Stop sound...
    delay(20);

    tone(BUZZER_PIN, BUZZER_FREQ, 80); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                // Stop sound...
    delay(20);
}

void HotspotStop_tone()
{
    tone(BUZZER_PIN, BUZZER_FREQ, 80); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                // Stop sound...
    delay(20);

    tone(BUZZER_PIN, BUZZER_FREQ, 80); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                // Stop sound...
    delay(20);

    tone(BUZZER_PIN, BUZZER_FREQ, 80); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                // Stop sound...
    delay(20);

    tone(BUZZER_PIN, BUZZER_FREQ, 80); // Send 1KHz sound signal...
    noTone(BUZZER_PIN);                // Stop sound...
    delay(20);
}